CC=gcc
CFLAGS=-Wall -O0 -pthread

all: deadlock1 deadlock2 hello pi_sequential pi_threaded racecondition1 racecondition2 spawn1 spawn2

clean:
	rm -f deadlock1 deadlock2 hello pi_sequential pi_threaded racecondition1 racecondition2 spawn1 spawn2
