CC=gcc-11
CFLAGS=-std=c99 -Wall -O3 -pthread

all: getid condvar fib_seq fib_threaded execution_random execution_ordered barrier_example once_key

clean:
	rm -f getid condvar fib_seq fib_threaded execution_random execution_ordered barrier_example once_key
